pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = 'DOCKERHUB_CREDENTIALS'  // Jenkins credential ID
        DOCKER_IMAGE_NAME = 'monish247/colorapp_jenkins'
        DOCKER_TAG = 'latest'
        DOCKER_USERNAME = 'monish247' // <-- Replace with your Docker Hub username
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Monish247/colorapp.git'
            }
        }

        stage('Restore Dependencies') {
            steps {
                dir('API-UI/webapi/ColorApi') {
                    sh 'dotnet restore'
                }
            }
        }

        stage('Build') {
            steps {
                dir('API-UI/webapi/ColorApi') {
                    sh 'dotnet build --configuration Release'
                }
            }
        }

        stage('Publish') {
            steps {
                dir('API-UI/webapi/ColorApi') {
                    sh 'dotnet publish --configuration Release --output ./publish'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('API-UI/webapi/ColorApi') {
                    sh "docker build -t ${DOCKER_IMAGE_NAME}:${DOCKER_TAG} -f Dockerfile ."
                }
            }
        }

        stage('Docker login and pushing image to Docker hub') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'dockerhub_pwd', variable: 'dockerhubpwd')]) {
                     sh 'docker login -u ${DOCKER_USERNAME}'
}
                    }

                    sh "docker push ${DOCKER_IMAGE_NAME}:${DOCKER_TAG}"
                }
            }
        }
    }

    post {
        success {
            echo '✅ Pipeline completed successfully!'
        }
        failure {
            echo '❌ Pipeline failed. Please check the logs.'
        }
    }
}
